### ISSUE TITLE
坐等更新

### ISSUE THREAD

**Issue by hsls010** [DocMine/AutoMJ#1]
教程一定要详细一点，我因为你这个项目决定开始学python……

**Comment by DocMine** [comment]
Got it，我这几天把它写详细点儿~
https://www.bilibili.com/video/BV12k4y1v7Eh/
这里是详细一些的操作视频~

**Comment by hsls010** [comment]
已三连+关注，之前一直卡在产图效率与人工成本上，你这个思路一下启发到我了。
十分感谢！
